services:
  - name: frontend
    image: anthonydip/todo-frontend:latest
    port: 80
    ingress:
      enabled: true
      path: "/"

  - name: backend
    image: anthonydip/todo-backend:latest
    port: 5000
    ingress:
      enabled: true
      path: "/api"
    env:
      DATABASE_URL: postgresql://postgres:password@database:5432/todos
      PORT: 5000

  - name: database
    image: postgres:15-alpine
    port: 5432
    env:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todos
